### ISSUE TITLE
Trying to get this going on a rpi 3b+, server running, wpe failing

### ISSUE THREAD

**Issue by cstoker2** [balena-io-playground/balena-dash-google-photos#2]
Vanilla install, getting this in logs: 

Failed to start service 'wpe sha256:150b43df4d6a8fa7703dd9ada5f0f8ea1cc3c621b51fef8f68a9d0b1b00bf708' due to '(HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/wpe-init\": permission denied": unknown '

**Comment by ympdev** [comment]
Everything seemed to be working fine... Balena logo splash appeared... and once I pushed the application to the remote, after a few mins. the Balena logo went away, and I'm left with a blank screen.

I added ALBUM_ID to the Environment Variables on the Balena Dashboard and set the value to my Google Photos album ID.

Any ideas what I'm missing?

**Comment by slashwithaknife** [comment]
> Vanilla install, getting this in logs:
> 
> Failed to start service 'wpe sha256:150b43df4d6a8fa7703dd9ada5f0f8ea1cc3c621b51fef8f68a9d0b1b00bf708' due to '(HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:296: starting container process caused "exec: "/wpe-init": permission denied": unknown '

I added line `RUN chmod +x wpe-init` /WPE/Dockerfile and now it works

**Comment by slashwithaknife** [comment]
> Everything seemed to be working fine... Balena logo splash appeared... and once I pushed the application to the remote, after a few mins. the Balena logo went away, and I'm left with a blank screen.
> 
> I added ALBUM_ID to the Environment Variables on the Balena Dashboard and set the value to my Google Photos album ID.
> 
> Any ideas what I'm missing?

I experienced something similar. After changing the fleet configuration`RESIN_HOST_CONFIG_gpu_mem` value to 396, it displays the slideshow.

**Comment by dansku** [comment]
Thank you @slashwithaknife, I will update the readme file for this!

**Comment by dansku** [comment]
@ympdev, I am revamping the project this week. I will ping you again to test it. 
Thank you
